name: web_content_parser_webviews
description: A parser for online content. This package defines a base design for the relation of data and parsing of it.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_content_parser:
    path: ../..
  flutter_inappwebview: ^5.4.1
