# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
     - camel_case_types
     - avoid_print
     - prefer_const_constructors
     - prefer_final_locals
     - always_declare_return_types

analyzer:
  errors:
    file_names: false
    constant_identifier_names: false
    omit_local_variable_types: ignore
  exclude:
    - packages/**
