name: web_content_parser
description: A parser for online content. This package defines a base design for the relation of data and parsing of it.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hetu_script: 0.3.12
  computer: ^3.1.0
  yaml: ^3.1.0
  path: ^1.8.0
  html: ^0.15.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  equatable: ^2.0.0
  convert: ^3.0.0
  intl: ^0.17.0
  puppeteer: ^2.4.0
  flutter_inappwebview: ^5.4.1

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^6.0.1
  lints: ^1.0.1
  test: ^1.17.10
  coverage: ^1.0.3
  dotenv: ^3.0.0
  petitparser: ^4.1.0
