name: web_content_parser
description: A parser for online content. This package defines a base design for the relation of data and parsing of it.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  computer: ^3.1.0
  yaml: ^3.1.0
  path: ^1.8.0
  html: ^0.15.0
  http: ^1.0.0
  json_annotation: ^4.4.0
  equatable: ^2.0.0
  convert: ^3.0.0
  intl: ^0.18.0
  petitparser: ^6.0.0

dev_dependencies:
  json2yaml: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.0.1
  lints: ^2.0.1
  test: ^1.17.10
  coverage: ^1.0.3
  js_bindings: ^0.1.2+1
  js: ^0.6.7
