name: web_content_headless
description: Provides implementations for a headless web browser for mobile and desktop.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web_content_headless_interface:
    git:
      url: https://github.com/Wetbikeboy2500/web_content_parser.git
      ref: dev
      path: packages/web_content_headless_interface
  web_query_framework_util:
    git:
      url: https://github.com/Wetbikeboy2500/web_content_parser.git
      ref: dev
      path: packages/web_query_framework_util
  flutter_inappwebview: ^5.4.1
  puppeteer: ^3.0.0
