name: web_content_headless
description: Provides implementations for a headless web browser for mobile and desktop.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_content_parser:
    git:
      url: https://github.com/Wetbikeboy2500/web_content_parser.git
      ref: dev
  flutter_inappwebview: ^5.4.1
  puppeteer: ^2.4.0
