name: web_query_framework_headless
description: Provides implementations for a headless web browser for mobile and desktop.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  web_query_framework_headless_interface:
    git:
      url: https://github.com/Wetbikeboy2500/web_query_framework.git
      ref: dev
      path: packages/web_query_framework_headless_interface
  web_query_framework_util:
    git:
      url: https://github.com/Wetbikeboy2500/web_query_framework.git
      ref: dev
      path: packages/web_query_framework_util
  flutter_inappwebview: ^5.4.1
  puppeteer: ^3.0.0
