# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests and code coverage
        env:
          SOURCE: ${{ secrets.SOURCE }}
          SUB: ${{ secrets.SUB }}
          BASE: ${{ secrets.BASE }}
        run: dart run tool/test.dart

      - uses: dorny/test-reporter@v1
        with:
          name: Dart Tests
          path: ./reports/tests.json
          reporter: dart-json
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
